import { SKILL_META } from '@zibby/skill-ids';
/**
 * artifact.js — publish a self-contained, shareable HTML/Markdown page.
 *
 * WHAT IT IS
 * ──────────
 * A hand-written multi-tool skill (same shape as kvMemory.js / datasetStore.js /
 * github.js): `serverName`, `allowedTools`, `tools[]`, `handleToolCall`, and a
 * `resolve()` that spawns the GENERIC bin/mcp-skill.mjs. It gives ANY agent (the
 * Copilot first) a way to PUBLISH a standalone page — a status report, a plan, a
 * comparison table, a dashboard-y summary, a diagram — to Zibby's own object
 * store and get back a shareable URL. Like Claude Code's Artifact tool, for Zibby
 * agents.
 *
 * TWO LAYERS — do NOT conflate (see strategy/artifact-generation-skill-2026-07.md)
 * ────────────────────────────────────────────────────────────────────────────
 *   - CONTENT (the rendered HTML/MD blob) → OBJECT STORE (ARTIFACTS_BUCKET). It's
 *     an OUTPUT, not memory. Written SERVER-SIDE by the control-plane so the
 *     object-store credentials never enter the hostile run container (invariant
 *     #5): the skill POSTs the content to POST {base}/artifacts and the backend
 *     does the privileged S3 write.
 *   - INDEX / metadata ({id,title,url,kind,createdAt,summary}) → kv-memory. "What
 *     I made" is structured MEMORY, so it rides the SHIPPED kv-memory layer
 *     (POST {base}/credits/review-memory, op 'store'/'recall', auto-namespaced by
 *     WORKFLOW_TYPE, IDENTICAL to kvMemory.js). `artifact_list` is therefore NOT a
 *     tool this skill defines — it is kv_recall_prefix('artifact:') on the shipped
 *     kv-memory skill (which the Copilot loads alongside this one). We write the
 *     index under the SAME scope shape kv-memory reads (`${ns}:artifact:<id>`) so a
 *     later kv_recall_prefix('artifact:') sees exactly the artifacts this agent
 *     published — no new store, no new table.
 *
 * MARKDOWN IS THE DEFAULT PATH — html is the justified exception
 * ──────────────────────────────────────────────────────────────
 * The two content fields are NOT equivalent. `html` is stored and served
 * VERBATIM: the model authors the whole document skeleton, so every publish is an
 * independent chance to get the skeleton wrong (five different skeletons for the
 * same page in one day; a raw markdown table; a double-escaped document whose
 * <!doctype> printed as text; bars with no width). `markdown` hands the skeleton
 * to OUR renderer — doctype, head, CSS, dark mode, typography and tables are all
 * generated by backend code — so that entire class of defect is structurally
 * impossible. Hence the contract below: markdown for anything report-shaped, html
 * ONLY for a layout Markdown cannot express. This is a TEMPLATE FREEZE, and it is
 * the single biggest lever on artifact success rate.
 *
 * VALIDATION + THE RETRY BUDGET — where each half lives
 * ─────────────────────────────────────────────────────
 * The RULES live in ONE place and it is not here: `backend/src/utils/
 * artifact-validate.js`, run by the handler this skill POSTs to. That is the
 * authoritative choke point (skill, CLI and every other agent pass through it),
 * and duplicating any rule here would be exactly the two-places drift the
 * codebase keeps getting burned by. This module implements ZERO validation. What
 * it DOES own is the piece a stateless handler cannot: a turn-local RETRY BUDGET.
 * Research on LLM HTML repair is unambiguous — later iterations rarely fix what
 * the first attempt got wrong — so after MAX_PUBLISH_ATTEMPTS rejected publishes
 * the tool stops the model and tells it to report the failure honestly instead of
 * burning turns or shipping a broken link.
 *
 * TOOLS
 * ─────
 *   artifact_publish({ title, html | markdown, kind?, favicon?, summary? })
 *        → control-plane writes the blob (ARTIFACTS_BUCKET, account+project scoped)
 *        → index record written to kv-memory (scope `${ns}:artifact:<id>`)
 *        → returns { id, url }
 *   artifact_update({ id, title?, html?|markdown? })  → same url, new version
 *   artifact_get({ id })                              → { metadata, content }
 *   (artifact_list = kv_recall_prefix('artifact:') on the kv-memory skill)
 *
 * AUTH — identical to kvMemory.js / datasetStore.js
 * ──────────────────────────────────────────────────
 * Calls ZIBBY'S OWN backend with PROJECT_API_TOKEN (Bearer) against
 * ZIBBY_ACCOUNT_API_URL (default api-prod.zibby.app). Tenancy (account + project)
 * is enforced SERVER-SIDE from the Bearer token — the skill NEVER sends
 * account/project. Mirrors @zibby/core/backend-client.js getSessionToken()/
 * getAccountApiUrl() rather than importing a non-existent helper.
 */

import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Resolve the generic skill MCP server binary — identical rationale to
 * kvMemory.js resolveSkillBin(): derive from import.meta.url so it works in
 * src/ (dev), dist/ (bundled), and node_modules/@zibby/skills/ (published).
 */
function resolveSkillBin() {
  if (process.env.MCP_SKILL_PATH) return process.env.MCP_SKILL_PATH;
  const here = dirname(fileURLToPath(import.meta.url));
  const candidate = resolvePath(here, '..', 'bin', 'mcp-skill.mjs');
  return existsSync(candidate) ? candidate : null;
}

/**
 * The run's backend credential. Mirrors @zibby/core/backend-client.js
 * getSessionToken(): prefer the Fargate-injected PROJECT_API_TOKEN, then the
 * dev ZIBBY_USER_TOKEN, then the local CLI session.
 */
function getSessionToken() {
  if (process.env.PROJECT_API_TOKEN) return process.env.PROJECT_API_TOKEN;
  if (process.env.ZIBBY_USER_TOKEN) return process.env.ZIBBY_USER_TOKEN;
  try {
    const p = join(homedir(), '.zibby', 'config.json');
    if (!existsSync(p)) return null;
    return JSON.parse(readFileSync(p, 'utf-8')).sessionToken || null;
  } catch {
    return null;
  }
}

/**
 * Account API base URL. Mirrors backend-client.js getAccountApiUrl():
 * explicit ZIBBY_ACCOUNT_API_URL (dev/local → ngrok) wins; otherwise default
 * to the live prod host.
 */
function getAccountApiUrl() {
  if (process.env.ZIBBY_ACCOUNT_API_URL) return process.env.ZIBBY_ACCOUNT_API_URL.replace(/\/$/, '');
  const env = process.env.ZIBBY_ENV || 'prod';
  if (env === 'local') return 'http://localhost:3001';
  return process.env.ZIBBY_PROD_ACCOUNT_API_URL || 'https://api-prod.zibby.app';
}

/**
 * The per-agent namespace prefix — IDENTICAL to kvMemory.js agentNamespace().
 * WORKFLOW_TYPE is injected into every Fargate run; fall back to the literal
 * 'agent' so the skill never crashes outside a run. Trimmed; an empty/
 * whitespace-only value also falls back. Keeping this byte-identical to
 * kv-memory is what makes `kv_recall_prefix('artifact:')` (which uses the same
 * namespacing) list exactly the artifacts this agent published.
 */
function agentNamespace() {
  const wt = typeof process.env.WORKFLOW_TYPE === 'string' ? process.env.WORKFLOW_TYPE.trim() : '';
  return wt || 'agent';
}

/** The kv-memory scope an artifact's index record lives at. */
function indexScope(id) {
  return `${agentNamespace()}:artifact:${id}`;
}

/**
 * What the model is told the markdown path CAN and CANNOT express. Kept as data
 * so the tool description, the prompt fragment and the retry advice all quote the
 * SAME list — and so a test can assert the description actually carries it.
 *
 * ⚠️ The authority for these strings is `backend/src/utils/markdown-lite.js`,
 * whose `MARKDOWN_CAPABILITIES` manifest is driven through the real renderer by
 * `backend/src/utils/__tests__/markdown-lite.test.js` (each `supports` entry must
 * render, each `lacks` entry must not). Promising a construct the renderer cannot
 * do would route content into a path that MANGLES it — the exact failure the
 * markdown default exists to remove. The two repos cannot share a file, so when
 * that manifest changes, change these strings in the same breath.
 */
const MARKDOWN_SUPPORTS =
  'headings, paragraphs, **bold**, *italic*, `inline code`, fenced code blocks, ' +
  'bullet + numbered lists, blockquotes, horizontal rules, links, and ' +
  'GitHub-style pipe tables (including |---:| alignment)';
const MARKDOWN_LACKS =
  'raw HTML (tags are escaped and print as literal text), images, nested lists, ' +
  'footnotes and strikethrough';

/**
 * How many REJECTED publishes the model may make before the tool stops it.
 *
 * Two, deliberately. The empirical finding on LLM HTML repair is that the first
 * attempt succeeds ~2/3 of the time and later iterations rarely fix what the
 * first got wrong — a third attempt roughly doubles cost for ~1% more success. So
 * the honest design is: constrain generation, validate once, allow ONE repair,
 * then stop and say so. A visible "I could not produce a clean page" beats a
 * silent broken link, and beats burning the user's turn budget pretending a
 * repair loop converges.
 */
const MAX_PUBLISH_ATTEMPTS = 2;

/**
 * Turn-local state: how many times IN A ROW the gate has rejected this agent's
 * content. The MCP child process is spawned per agent session, so this is
 * effectively per-turn for the Copilot. It resets on any successful publish, so a
 * long run that legitimately publishes several pages is never penalised for an
 * earlier one — only CONSECUTIVE failures trip the stop.
 */
let consecutiveRejections = 0;

/** Test hook — the budget is process-lifetime state, so a suite must clear it. */
export function __resetPublishBudget() { consecutiveRejections = 0; }

/** The stop-and-be-honest payload, returned once the budget is spent. */
function budgetExhausted(lastError, lastDefects) {
  return JSON.stringify({
    published: false,
    stop: true,
    attemptsUsed: MAX_PUBLISH_ATTEMPTS,
    defects: lastDefects || [],
    error: lastError,
    instruction:
      `STOP. You have used both publish attempts and the page is still rejected. Do NOT call ` +
      `artifact_publish or artifact_update again in this turn. Tell the user plainly that you could ` +
      `not produce a clean page, say in one line what was wrong, and give them the content directly ` +
      `in the chat instead. A broken link is worse than an honest "I couldn't".`,
  });
}

/** The fix-it-once payload, returned on the FIRST rejection. */
function retryOnce(format, error, defects) {
  return JSON.stringify({
    published: false,
    stop: false,
    attemptsRemaining: MAX_PUBLISH_ATTEMPTS - consecutiveRejections,
    defects: defects || [],
    error,
    instruction:
      `The page was NOT published and no URL exists. Fix EXACTLY the defects listed above and call ` +
      `once more — you get ONE more attempt, then this tool will stop you.` +
      (format === 'html'
        ? ` You are on the \`html\` path, where you author the entire document and every mistake ships. ` +
          `Unless this page genuinely needs a custom visual layout, the fastest and most reliable fix is ` +
          `to re-send the SAME content as \`markdown\` — Zibby then generates the document skeleton, CSS ` +
          `and tables for you and these defects become impossible. Markdown supports ${MARKDOWN_SUPPORTS}.`
        : ` Markdown supports ${MARKDOWN_SUPPORTS}; it does NOT support ${MARKDOWN_LACKS}.`),
  });
}

/**
 * POST {base}/artifacts — the privileged, SERVER-SIDE blob write. Body carries
 * the content ({ title, html|markdown, kind?, favicon?, id? }); the backend does
 * the S3 PutObject (ARTIFACTS_BUCKET) so object-store creds never enter this run.
 * Returns { id, url, ... }.
 *
 * On a non-2xx it throws an Error carrying `.status` and (for a 422 from the
 * validation gate) `.defects` — the structured list of what is wrong and where.
 * The caller distinguishes "your page is broken" (422, retryable, budgeted) from
 * every other failure (auth, quota, outage — not the model's to fix).
 */
async function artifactWriteFetch(payload) {
  const session = getSessionToken();
  if (!session) {
    throw new Error('No backend credential (PROJECT_API_TOKEN). Artifacts are only available inside a Zibby run.');
  }
  // '/credits/artifacts', not '/artifacts': on cloud the main API sits at its
  // 500-resource cap, so these routes live on the credits RestApi (same
  // placement as review-memory below); self-host mounts the same alias.
  const res = await fetch(`${getAccountApiUrl()}/credits/artifacts`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${session}`, 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    let parsed: any = null;
    try { parsed = JSON.parse(body); } catch { /* not JSON — fall back to the raw text */ }
    // 422 = the publish GATE refused the content. Keep the full message (it names
    // each defect and its line); truncating it would defeat the whole point.
    const err: any = new Error(
      res.status === 422 && parsed?.error
        ? parsed.error
        : `artifact write failed (${res.status}): ${body.slice(0, 300)}`,
    );
    err.status = res.status;
    if (Array.isArray(parsed?.defects)) err.defects = parsed.defects;
    throw err;
  }
  return res.json();
}

/**
 * artifactWriteFetch + the retry budget. Returns the backend's success object, or
 * `{ __rejected: true, payload }` where `payload` is the exact string the tool
 * hands back to the model (fix-it-once, or stop-and-be-honest).
 *
 * ONLY a 422 — the validation gate saying "this page is broken" — consumes the
 * budget. Auth failures, quota, and outages are not the model's to repair and are
 * rethrown untouched. A success RESETS the budget, so publishing several good
 * pages in one run is never penalised by an earlier bad one.
 */
async function publishWithBudget(payload, format) {
  try {
    const written = await artifactWriteFetch(payload);
    consecutiveRejections = 0;
    return written;
  } catch (e: any) {
    if (e?.status !== 422) throw e;
    consecutiveRejections += 1;
    const out = consecutiveRejections >= MAX_PUBLISH_ATTEMPTS
      ? budgetExhausted(e.message, e.defects)
      : retryOnce(format, e.message, e.defects);
    return { __rejected: true, payload: out };
  }
}

/** GET {base}/artifacts/{id} — authenticated fetch of one artifact's metadata + source content. */
async function artifactReadFetch(id) {
  const session = getSessionToken();
  if (!session) {
    throw new Error('No backend credential (PROJECT_API_TOKEN). Artifacts are only available inside a Zibby run.');
  }
  const res = await fetch(`${getAccountApiUrl()}/credits/artifacts/${encodeURIComponent(id)}`, {
    method: 'GET',
    headers: { Authorization: `Bearer ${session}` },
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`artifact get failed (${res.status}): ${body.slice(0, 300)}`);
  }
  return res.json();
}

/**
 * Upsert the artifact's INDEX record into kv-memory (the SAME route + table the
 * kv-memory skill uses). op 'store' preserves createdAt server-side across
 * upserts (review-memory.js keeps the first createdAt), so an update never loses
 * the original creation time. Best-effort caller: publish/update surface the
 * error but the blob is already written.
 */
async function indexStore(id, record) {
  const session = getSessionToken();
  if (!session) return; // no run credential → nothing to index against
  const res = await fetch(`${getAccountApiUrl()}/credits/review-memory`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${session}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ op: 'store', scope: indexScope(id), content: JSON.stringify(record) }),
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`artifact index write failed (${res.status}): ${body.slice(0, 200)}`);
  }
}

/** Recall the existing index record for `id` (returns the parsed object or null). */
async function indexRecall(id) {
  const session = getSessionToken();
  if (!session) return null;
  const res = await fetch(`${getAccountApiUrl()}/credits/review-memory`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${session}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ op: 'recall', scope: indexScope(id) }),
  });
  if (!res.ok) return null;
  const data = await res.json().catch(() => null);
  if (!data?.found || !data?.memory?.content) return null;
  try { return JSON.parse(data.memory.content); } catch { return null; }
}

/**
 * Pull the ONE content field out of args → { format, content }, or an { error }
 * the caller returns verbatim, or null when neither field is present.
 *
 * Passing BOTH is now an explicit error rather than "html silently wins": the two
 * paths produce visibly different pages, so guessing which one the model meant is
 * how you ship the wrong format.
 */
function pickContent(args) {
  const hasHtml = typeof args?.html === 'string' && args.html.length > 0;
  const hasMd = typeof args?.markdown === 'string' && args.markdown.length > 0;
  if (hasHtml && hasMd) {
    return { error: 'Pass EITHER markdown OR html, not both — they are different rendering paths. Use markdown unless the page needs a custom visual layout.' };
  }
  if (hasMd) return { format: 'markdown', content: args.markdown };
  if (hasHtml) return { format: 'html', content: args.html };
  return null;
}

export const artifactSkill: any = {
  id: 'artifact',
  // Backend-calling: the MCP child talks to Zibby's own backend — the
  // session-env contract is guaranteed by backendSession.ts at registration
  // (declare ONCE here; see backend-session-env-contract.test.ts).
  callsBackend: true,
  // ONE source for toggle metadata — by reference, never a copy (skills-platform rule).
  meta: SKILL_META['artifact'],
  serverName: 'artifact',
  allowedTools: ['mcp__artifact__*'],
  description: 'Artifacts — publish a self-contained, shareable HTML/Markdown page to Zibby and get back a URL; the index of what you published is your memory.',

  promptFragment: `## Artifacts (publish a shareable page, remember what you made)
You can PUBLISH a standalone page — a status report, a plan, a comparison table,
a dashboard-y summary, a diagram, a "here's what I found" write-up — and get back
a shareable URL.

### WRITE IT AS MARKDOWN. That is the default, and it is not a stylistic hint.
Pass \`markdown\` and Zibby generates the whole document for you — doctype, head,
CSS, typography, dark mode, table styling. You supply only the CONTENT. Markdown
supports ${MARKDOWN_SUPPORTS}. It does NOT support ${MARKDOWN_LACKS}.

Pass \`html\` ONLY when the page genuinely needs a visual layout Markdown cannot
express — a bar chart, a gauge, a custom grid, an SVG diagram. On the html path
YOU author the entire document and every mistake ships: a table left in Markdown
syntax, an escaped \`&lt;!doctype\`, a bar with no width. If the page is a report,
a plan, a list, a table or a write-up, it is markdown. No exceptions worth taking.

Whichever path: the page is sandboxed when viewed (no network at all, no ambient
credentials), so on the html path keep ALL CSS/JS/images INLINE (inline
<style>/<script>, data: URIs) — every external URL is blocked and will simply not
load. NEVER escape the document: send real tags, not \`&lt;div&gt;\`.

### Every number on the page must come from a tool result or this transcript.
Do not do arithmetic in prose and then print the answer — that is how a page ends
up saying 42 in one place and 45 in another. If you need a total, compute it with
a tool (or restate the figures exactly as your tools returned them) and cite the
same figure everywhere it appears.

### The page is validated BEFORE a URL exists.
If the content is broken you get back the exact defects and their line numbers,
and no page is created. You get ONE retry. After that the tool STOPS you — at
which point say plainly that you could not produce a clean page and put the
content in the chat instead. Do not keep trying.

THE CONTENT COMES FROM THIS CONVERSATION — NEVER FROM YOUR IMAGINATION.
When someone says "make me a page / an artifact / a report", they mean THE THING
YOU WERE JUST TALKING ABOUT. Build the page from what is actually in this
transcript (or from data you fetch with your tools THIS turn for that specific
subject). The page is about the USER'S subject matter — their tickets, their
repos, their incidents, their data.

If you do NOT know what the page should be about — the request is vague and the
transcript does not tell you — then ASK ONE SHORT QUESTION ("which part should I
turn into a page?") and publish NOTHING. Do NOT fall back on a demo, a sample, a
placeholder, or a "here's an overview of your account" page, and do NOT go
inventory the account (projects / agents / integrations) just to have something to
render. A page the user did not ask for is worse than a question: it wastes the
link, buries the real answer, and reads as if you ignored them. There is no
situation in which "示例 / sample / demo" belongs in a title you publish.

Tools:
- artifact_publish: Publish a NEW page. Pass a \`title\` and EITHER \`markdown\`
  (the default — prefer this) OR \`html\` (never both). Optional \`kind\` (e.g.
  "report", "plan", "dashboard"), \`favicon\` (an emoji), and \`summary\` (one line
  for your own index). Returns { id, url }. Share the url; keep the id if you'll
  update it later.
- artifact_update: Revise an EXISTING page by \`id\` (same url, new version). Pass
  the fields to change (\`title\`, \`markdown\`|\`html\`).
- artifact_get: Fetch one artifact by \`id\` → { metadata, content } so you can
  reuse / edit / re-publish it.

To recall WHAT YOU HAVE ALREADY PUBLISHED, use your kv-memory tool
kv_recall_prefix with keyPrefix "artifact:" — each entry is the index record
{ id, title, url, kind, createdAt, summary } for a page you made. (Publishing
records this automatically; you don't store it yourself.)`,

  resolve() {
    // Spawn the GENERIC skill MCP server (bin/mcp-skill.mjs) pointing at this
    // module's artifactSkill export — same FIXED pattern as kvMemory/datasetStore
    // (NEVER return { command: null }). The module arg resolves relative to bin/
    // at runtime → ../dist/artifact.js in a published install.
    const bin = resolveSkillBin();
    if (!bin) return { command: null, args: [], env: {}, description: this.description };
    const env: any = {};
    for (const key of [
      'PROJECT_API_TOKEN', 'ZIBBY_ACCOUNT_API_URL', 'ZIBBY_ENV', 'ZIBBY_PROD_ACCOUNT_API_URL', 'ZIBBY_USER_TOKEN',
      // The namespace source (matches kv-memory) so the index scope lines up.
      'WORKFLOW_TYPE',
    ]) {
      if (process.env[key]) env[key] = process.env[key];
    }
    return {
      type: 'stdio',
      command: 'node',
      args: [bin, '../dist/artifact.js', 'artifactSkill'],
      env,
      description: this.description,
      // Force tools into the system prompt instead of deferring behind the SDK's
      // ToolSearch (same as kvMemory.js) — the Copilot loads this as a CORE skill.
      alwaysLoad: true,
    };
  },

  async handleToolCall(name, args) {
    try {
      switch (name) {
        case 'artifact_publish': {
          if (consecutiveRejections >= MAX_PUBLISH_ATTEMPTS) return budgetExhausted('Publish budget already spent this turn.', []);
          const title = typeof args?.title === 'string' ? args.title.trim() : '';
          if (!title) return JSON.stringify({ error: 'title is required' });
          const picked = pickContent(args);
          if (!picked) return JSON.stringify({ error: 'provide exactly one of markdown (preferred) or html (non-empty string)' });
          if (picked.error) return JSON.stringify({ error: picked.error });

          const payload: any = { title, [picked.format]: picked.content };
          if (typeof args?.kind === 'string' && args.kind.trim()) payload.kind = args.kind.trim();
          if (typeof args?.favicon === 'string' && args.favicon.trim()) payload.favicon = args.favicon.trim();

          const written = await publishWithBudget(payload, picked.format); // { id, url, createdAt, ... } | { __rejected }
          if (written?.__rejected) return written.payload;
          const id = written?.id;
          const url = written?.url;
          if (!id || !url) return JSON.stringify({ error: 'artifact write returned no id/url', response: written });

          const record: any = {
            id,
            title,
            url,
            kind: payload.kind || null,
            createdAt: written.createdAt || new Date().toISOString(),
            summary: typeof args?.summary === 'string' && args.summary.trim() ? args.summary.trim() : title,
          };
          try { await indexStore(id, record); } catch (e) {
            // Blob is published; surface the index warning but don't fail the publish.
            return JSON.stringify({ id, url, indexWarning: e.message });
          }
          return JSON.stringify({ id, url });
        }

        case 'artifact_update': {
          if (consecutiveRejections >= MAX_PUBLISH_ATTEMPTS) return budgetExhausted('Publish budget already spent this turn.', []);
          const id = typeof args?.id === 'string' ? args.id.trim() : '';
          if (!id) return JSON.stringify({ error: 'id is required' });
          const picked = pickContent(args);
          if (picked?.error) return JSON.stringify({ error: picked.error });
          const title = typeof args?.title === 'string' ? args.title.trim() : '';
          if (!picked && !title) {
            return JSON.stringify({ error: 'nothing to update — pass a new title and/or markdown|html' });
          }
          const payload: any = { id };
          if (title) payload.title = title;
          if (picked) payload[picked.format] = picked.content;
          if (typeof args?.kind === 'string' && args.kind.trim()) payload.kind = args.kind.trim();
          if (typeof args?.favicon === 'string' && args.favicon.trim()) payload.favicon = args.favicon.trim();

          const written = await publishWithBudget(payload, picked?.format); // { id, url, updatedAt, createdAt? }
          if (written?.__rejected) return written.payload;
          const url = written?.url;
          if (!url) return JSON.stringify({ error: 'artifact update returned no url', response: written });

          // Merge the index record: keep the original createdAt (recall it), bump
          // updatedAt + any changed fields.
          const prior = (await indexRecall(id)) || {};
          const record: any = {
            ...prior,
            id,
            url,
            title: title || prior.title || 'Untitled',
            kind: payload.kind || prior.kind || null,
            createdAt: prior.createdAt || written.createdAt || new Date().toISOString(),
            updatedAt: written.updatedAt || new Date().toISOString(),
          };
          if (typeof args?.summary === 'string' && args.summary.trim()) record.summary = args.summary.trim();
          else if (!record.summary) record.summary = record.title;
          try { await indexStore(id, record); } catch (e) {
            return JSON.stringify({ id, url, indexWarning: e.message });
          }
          return JSON.stringify({ id, url });
        }

        case 'artifact_get': {
          const id = typeof args?.id === 'string' ? args.id.trim() : '';
          if (!id) return JSON.stringify({ error: 'id is required' });
          const data = await artifactReadFetch(id); // { metadata, content }
          return JSON.stringify(data);
        }

        default:
          return JSON.stringify({ error: `Unknown tool: ${name}` });
      }
    } catch (e) {
      return JSON.stringify({ error: e.message });
    }
  },

  tools: [
    {
      name: 'artifact_publish',
      description:
        'Publish a NEW self-contained, shareable page (report/plan/table/dashboard/diagram/write-up) and get back a shareable URL. '
        + 'USE `markdown` — it is the default path and Zibby generates the entire document for you (doctype, head, CSS, dark mode, table styling); you supply only the content, so the page cannot come out malformed. '
        + `Markdown supports ${MARKDOWN_SUPPORTS}; it does NOT support ${MARKDOWN_LACKS}. `
        + 'Use `html` ONLY when the page needs a visual layout Markdown cannot express (a bar chart, a gauge, a custom grid, an SVG diagram) — on that path you author the whole document and every mistake ships verbatim. Never pass both. '
        + 'Every figure on the page must come from a tool result or this conversation — do not do arithmetic in prose and print the result, and use the same number everywhere it appears. '
        + 'The content MUST come from the current conversation or data you fetched this turn; if you are not sure what the page should be about, ASK instead of calling this tool, and never publish a demo/sample/placeholder or an account-overview page as a stand-in. '
        + 'On the html path keep all CSS/JS/images INLINE (inline <style>/<script>, data: URIs) and send real tags (never &lt;escaped&gt; markup) — the page is sandboxed on view with no network at all, so every external URL is dead. '
        + 'The content is VALIDATED before any URL exists: if it is broken you get the exact defects and line numbers back, you get ONE retry, and then the tool stops you. Returns { id, url }.',
      input_schema: {
        type: 'object',
        properties: {
          title: { type: 'string', description: 'The page title (also the browser tab title).' },
          markdown: { type: 'string', description: `PREFERRED. The page content as Markdown — Zibby renders it into a styled, self-contained document, so you never author a skeleton. Supports ${MARKDOWN_SUPPORTS}. Does NOT support ${MARKDOWN_LACKS}. Provide this OR html, never both.` },
          html: { type: 'string', description: 'The EXCEPTION path — only for a layout Markdown cannot express (bar chart, gauge, custom grid, SVG diagram). A self-contained HTML document or fragment, served VERBATIM: you own the doctype, head, CSS and every tag. All assets must be inline (<style>/<script>, data: URIs). Provide this OR markdown, never both.' },
          kind: { type: 'string', description: 'Optional label for what this is, e.g. "report", "plan", "dashboard", "diagram". Stored in your index.' },
          favicon: { type: 'string', description: 'Optional emoji used as the browser-tab icon, e.g. "📊".' },
          summary: { type: 'string', description: 'Optional one-line summary for your own index (defaults to the title). Helps you recall later what this page was.' },
        },
        required: ['title'],
      },
    },
    {
      name: 'artifact_update',
      description:
        'Revise an EXISTING artifact by id — the shareable URL stays the same, the content is replaced (new version). Pass the fields to change (title and/or markdown|html). '
        + 'Prefer `markdown` for the same reason artifact_publish does: Zibby generates the document, so it cannot come out malformed. An update is validated exactly like a publish — if the new content is broken it is REFUSED and the page keeps its last good version. Returns { id, url }.',
      input_schema: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'The id of the artifact to update (from a prior artifact_publish, or your kv-memory "artifact:" index).' },
          title: { type: 'string', description: 'New title (optional).' },
          markdown: { type: 'string', description: `PREFERRED. New Markdown content (optional) — Zibby renders the document skeleton. Supports ${MARKDOWN_SUPPORTS}. Provide this OR html.` },
          html: { type: 'string', description: 'New HTML content (optional), served verbatim — only for layouts Markdown cannot express. Provide this OR markdown.' },
          kind: { type: 'string', description: 'Optional updated kind label.' },
          favicon: { type: 'string', description: 'Optional updated emoji favicon.' },
          summary: { type: 'string', description: 'Optional updated one-line index summary.' },
        },
        required: ['id'],
      },
    },
    {
      name: 'artifact_get',
      description: 'Fetch ONE artifact you published, by id → { metadata, content }. Use to reuse / edit / re-publish a page. To LIST what you have published, use your kv-memory tool kv_recall_prefix with keyPrefix "artifact:".',
      input_schema: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'The artifact id.' },
        },
        required: ['id'],
      },
    },
  ],
};
